let data = [
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "api",
    type: "folder",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "README.md",
    type: "script",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
  {
    name: "ya.make",
    type: "doc",
    commit: "d53dsv",
    commit_info: "by Alexey Besedin, 4 s ago",
    message: "[vcs] move http to arc",
    committer: "noxoomo",
    updated: "4 s ago",
  },
];

export default data;
